name: CI-Posts

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Backend/Posts/*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .net environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      - name: dotnet build
        working-directory: src/Backend/Posts
        run: dotnet build

      - name: dotnet test
        working-directory: src/Backend/Posts
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: publish code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: src/Backend/Posts/test/Posts.Domain.Test/TestResults/coverage.info
